sudo: false

language: node_js

# https://github.com/nodejs/Release
node_js:
  - '12'
  - '10'
  - '8'

git:
  depth: 5

cache: yarn

before_install:
  - npm config set spin false --global

script:
  # FIXME: disable coverage report for now, because isparta coverage break tests
  # - if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then npm run lint && npm run check && npm run cover:lcov; else npm run testonly; fi
  # FIXME: disable linting because a mutually exclusive rule always fails
  #- if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then npm run lint && npm run check && npm run testonly; else npm run testonly; fi
  - npm run testonly


#after_failure:
  #  - (cd resources; python travis_after_all.py)

# after_success:
  #  - (cd resources; python travis_after_all.py)
  #  - export $(cat resources/.to_export_back)
  # FIXME: disable coverage report for now, because isparta coverage break tests
  # - if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
